---
schema:
  procedures: {}
  tables:
    todolist:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - todolist_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        entry:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: entry
          order: 2
          size:
            - 0
        status:
          data_type: enum
          default_value: ~
          extra:
            list: &1
              - open
              - closed
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: status
          order: 3
          size:
            - 0
        todolist_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: todolist_id
          order: 1
          size:
            - 0
      indices: []
      name: todolist
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    DBIx::Class::Schema: ~
    DBIx::Schema: ~
    package: &2 !!perl/hash:CatalystX::Example::Todo::Schema
      class_mappings:
        CatalystX::Example::Todo::Schema::Result::TodoList: TodoList
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
      source_registrations:
        TodoList: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            entry:
              data_type: text
            status:
              data_type: enum
              default: open
              extra:
                list: *1
            todolist_id:
              data_type: integer
              is_auto_increment: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - todolist_id
            - entry
            - status
          _primaries: &3
            - todolist_id
          _relationships: {}
          _unique_constraints:
            primary: *3
          name: todolist
          result_class: CatalystX::Example::Todo::Schema::Result::TodoList
          resultset_attributes: {}
          resultset_class: CatalystX::Example::Todo::Schema::ResultSet::TodoList
          schema: *2
          source_name: TodoList
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &4
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *4
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *2
          source_name: __VERSION
      storage: !!perl/hash:DBIx::Class::Storage::DBI::SQLite
        _conn_pid: 969
        _connect_info:
          - DBI:SQLite:/Users/john/Desktop/CatalystX-Example-Todo/share/catalystx-example-todo-schema.db
          - ''
          - ''
        _dbh: !!perl/hash:DBI::db {}
        _dbh_autocommit: 1
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - DBI:SQLite:/Users/john/Desktop/CatalystX-Example-Todo/share/catalystx-example-todo-schema.db
          - ''
          - ''
          - &5
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
            ShowErrorStatement: 1
        _dbic_connect_attributes: *5
        _driver_determined: 1
        _in_do_block: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        savepoints: []
        schema: *2
        transaction_depth: 0
    sources:
      - TodoList
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11016
